### ISSUE TITLE
"invalid values" sneaking into spectral_whitening

### ISSUE THREAD

**Issue by filefolder** [trichter/yam#10]
Hi again, rare error but sometimes it would appear that either a nan or inf can find its way into spec_ampl in correlate.spectral_whitening.

```
.local/lib/python3.6/site-packages/yam/correlate.py:232: RuntimeWarning: invalid value encountered in less
  spec_ampl[spec_ampl < waterlevel] = waterlevel
```

adding `spec_ampl = np.nan_to_num(spec_ampl)` before `spec_ampl[spec_ampl < waterlevel] = waterlevel` line 208ish seems to be a painless way around it

**Comment by trichter** [comment]
Interesting. Can you find out more about this case? I could imagine that the whole spectrum are nans or infs.

**Comment by trichter** [comment]
> I'll keep an eye on it, can confirm that the issue is all nan's at least.

One NaN in the time series is enough to get a spectrum full of NaNs...

In this case, your suggested patch is not the way to go. It is better to find out more about the root of the problem. One way to debug it, is to turn the warning into an error and start a debugger upon error.

**Comment by filefolder** [comment]
OK-- somehow some small traces with different network IDs were found in random the daily miniseed files. Yikes

Then at some point (in preprocess?) these traces were converted from having valid data to being all zeros (an effect of trying to merge data with different metadata?), which shouldn't be an issue necessarily until `spec_ampl /= max(spec_ampl)` which then is dividing by zero and the source of the nans. 

I'm not sure how relevant a problem this would be in the general circumstance of dealing with the occasional zero'd trace data, but I guess you could quickly just short circuit out of spectral_whitening with a `if np.max(spec_ampl) == 0: return tr` or something, which is what I'm going with for now.

**Comment by trichter** [comment]
Ah, OK, would be interesting which operation introduces the zeros.

> Probably makes more sense to test if tr.data is all zeros somewhere but not sure where would be most efficient.

Agreed. Maybe [line 461](https://github.com/trichter/yam/blob/5bfe35f533c22414d1561cd1ae776abef91c5fa6/yam/correlate.py#L461) in correlate.py is a good place. I will see.

**Comment by trichter** [comment]
Closing for now. Please reopen if necessary.
