### ISSUE TITLE
Stacking issue [if stacking within "correlate 1" option]

### ISSUE THREAD

**Issue by teglik** [trichter/yam#11]
I have encountered a problem with correlation stacking.

I correlated data with "correlate 1" option, and I also set there to do 1-hour stacks (i.e., "stack": "1h"). However, there is a 1-hour gap each 24 hours. See the enclosed conf.txt file and the example plots:

[conf.txt](https://github.com/trichter/yam/files/7075605/conf.txt)
Note: conf file extension was changed just because of a compatibility issue while uploading.

![corr_vs_time_c1_s1h_5E S301-5E S302_ HHZ- HHZ](https://user-images.githubusercontent.com/89773974/131316993-a2c776b8-4478-4678-901b-7705d8aed7b8.png)
![corr_vs_time_c1_s1h_5E S301-5E S302_ HHZ- HHZ](https://user-images.githubusercontent.com/89773974/131317662-cb8c178e-edf0-4152-a99d-c74a4a932ab8.png)

However, if the 1-hour stacking is done by the "stack 1" option, no such problem occurs.

**Comment by trichter** [comment]
Thanks for reporting this issue.

I think I included this "feature" as a safety measure to guarantee that all traces in the stack originate from the same number of traces. Therefore, the last trace(s) in each stack stream is ignored. This is no big deal when performing the stack for a long data set. But when using (a non-standard) stack option inside correlate, it surfaces in your issue.

Line 52 of `stack.py` reads
```
t2 = max(t1, traces[-1].stats.endtime - lensec)
```
If you remove the `- lensec` the issue should go away. The downside: When using option `overlap` inside correlate, one or more traces for each day inside the stack will originate from a lower number of correlated traces.

The best option might be to use `- lensec + movesec` which should ignore the last trace(s) only if it is really necessary.
Maybe you could check this.

**Comment by trichter** [comment]
No feedback for a while, closing for now.
