### ISSUE TITLE
Plots not working on fresh install

### ISSUE THREAD

**Issue by flofux** [trichter/yam#12]
Hey Tom,
after some while I started using your tool again - I simply like it :)

However, within a fresh conda environment and trying to reproduce your tutorial notebook I get the following error when trying to plot:

`!yam plot c1_s1_t1b --plot-options '{"show_line": true, "vmax": 1, "ylim": 0.8}'`
`yam plot: error: argument --plot-options: invalid loads value: "'{show_line:"`

or similarly:

`!yam plot c1_s1 --plot-options '{"xlim": [0, 20], "vmax": 0.01}'`
`yam plot: error: argument --plot-options: invalid loads value: "'{xlim:"`

Any idea? ;-) Thanks!

**Comment by trichter** [comment]
Hey Flo,

thanks :)

The error indicates that the argument passed to `--plot-options` is not valid JSON. It should be. And indeed in the error message the `"` is missing around `show_line`. Maybe the command in the tutorial is only working for bash and you are using another shell?

**Comment by flofux** [comment]
Hey Tom,

that was fast! Yeah, it's probably that. I was working on a windows machine ... (shame on me, yes). On another Linux machine everything worked just fine.
