### ISSUE TITLE
Issue when running tutorial notebook 

### ISSUE THREAD

**Issue by ThomasMGeo** [trichter/yam#13]
![Screen Shot 2023-03-20 at 4 40 12 PM](https://user-images.githubusercontent.com/38228140/226481571-ed28e572-257c-48d4-81e9-fdc089804b72.png)

Short screengrab. Happy to go into detail further.

**Comment by trichter** [comment]
Thanks for reporting. The install process should have registered the command `yam`.  Did you install yam into a conda environment? Are you running the notebook server in the same environment?

**Comment by ThomasMGeo** [comment]
> did you install yam into a conda environment?

I did not, is that a requirement? I am using a research jupyterhub, but I can test locally as well.

**Comment by ThomasMGeo** [comment]
Ah! I see your installation notes now, I would put that on the readme :).

**Comment by trichter** [comment]
I think it just needs to be installed in some way, because the cli-script is registered in the setup.py file
