### ISSUE TITLE
Yam Plotting Issue

### ISSUE THREAD

**Issue by ThomasMGeo** [trichter/yam#14]
When running the tutorial notebook, !yam info works great, but I am getting an error when running 

```
!yam plot data CX.PB01..HHZ 2020-01-01
Image("plots/data_CX.PATCX..HHZ_2020-01-01.png", width=600)
```
<img width="1049" alt="Screen Shot 2023-03-21 at 11 30 12 AM" src="https://user-images.githubusercontent.com/38228140/226693295-ed69efad-e68f-4361-9629-870cadf8b817.png">

With the newest version of Yam
<img width="317" alt="Screen Shot 2023-03-21 at 11 31 29 AM" src="https://user-images.githubusercontent.com/38228140/226693426-c7f0b90f-f649-4034-99d3-2883b523435c.png">

**Comment by trichter** [comment]
Did the download of the data in cell 2 succeed? It takes a while to download  the requested month of raw data. Could you rerun cell 2? Already downloaded data will not be downloaded again.

**Comment by ThomasMGeo** [comment]
I just re-ran it again, cell 2 ran fine, and still have the same error. Attached is my notebook in a zip file.


[xcorr_ipoc.ipynb.zip](https://github.com/trichter/yam/files/11033554/xcorr_ipoc.ipynb.zip)

**Comment by trichter** [comment]
Ups. In cell 5 it should read

```
!yam plot data CX.PB01..HHZ 2020-01-01
Image("plots/data_CX.PB01..HHZ_2020-01-01.png", width=600)
```

I will change cell 5 and 6 to consistently use station PB01.
