### ISSUE TITLE
Does Yam integrate with Pandas?

### ISSUE THREAD

**Issue by ThomasMGeo** [trichter/yam#15]

**Comment by trichter** [comment]
No yam does not integrate with pandas. Though, results are saved in HDF5 files. These could be read with pandas. In my opinion, time series and matrix capabilities of NumPy and SciPy are enough to explore and continue processing results.

**Comment by ThomasMGeo** [comment]
Might be worth showing that workflow, just so it can integrate better with other parts of the scientific python stack.

**Comment by trichter** [comment]
cc https://github.com/openjournals/joss-reviews/issues/5267
