### ISSUE TITLE
stations order in the cross-correlations are not in the same order defined in conf.json

### ISSUE THREAD

**Issue by alemkhodadadi** [trichter/yam#18]
After plotting the cross correlations, I see asymmetric arrivals so I wanted to have all the strong arrivals in the casual side. so I tried to change the order between the station1 and station2 in  the parameter _station_combinations_ in the conf.json file. 
so I changed 
`"station_combinations": ["PK-PM"]`
to
`"station_combinations": ["PM-PK"]`
but after running the _correlate_ command, I checked the generated _stack.h5_ again but the trace id for PM-PK is still `'PK.DPT.PM.DPT'` .
It happens for all other pairs also. My question is, is the code re-ordering the station pairs alphabetically? 
I also tried to reverse the data array in some traces in the final H5 file with` obspy.Stream.write` function but it ended up with corruption in the group names in the h5 file and the package (yam) cannot read the stack file again for example for plotting or checking the info.  
What would you suggest to have the desired order of stations in all station-pairs?

**Comment by alemkhodadadi** [comment]
I temporarily solved my problem just in plotting by adding an extra argument _station_order_change=None_ to the function _plot_corr_vs_dist_ in the imaging.py file. I put the ids of the pairs that I need to be reversed and it just changes the order of the trace data just before plotting them.
`
def plot_corr_vs_dist(
        stream, fname=None, figsize=(20, 10), ext='png', dpi=None,
        components='ZZ', scale=1, dist_unit='km',
        xlim=None, ylim_low=None, ylim_up=None, time_period=None, plot_kw={}, station_order_change=None):
        ###
        for tr in stack:
            if station_order_change is not None:
                if tr.id in station_order_change:
                    tr.data = tr.data[::-1]
        ###
`

**Comment by trichter** [comment]
Yes, the `station_combinations` parameter is just for filtering. It does not change the order of stations in the xcorr. These are sorted by name. Glad, that you found a workaround for plotting.

I think it should work to add a check [at line 662 in correlate.py](https://github.com/trichter/yam/blob/master/yam/correlate.py#L662) and exchange station1 and station2 variables if they are in the "wrong" order.

Maybe something like this will work (untested):
```
        if station_combinations and not any(station_comb.split('-') == (
                [station1.rsplit('.', 2)[0], station2.rsplit('.', 2)[0]]
                if '.' in (station_comb) else
                [station1.split('.')[1], station2.split('.')[1]])
                for station_comb in station_combinations):
            station1, station2 = station2, station1
```

For this I took the check from lines 656-661 and replaced occurrences of sets with lists. Therefore the stations are switched if they are in the station_combinations (check in the lines before) , but not in the correct order.

**Comment by alemkhodadadi** [comment]
thank you for your reply. the code changes the order in an almost random way. I added some lines in which the code checks with the station-pair that its working on and changes the order if it is in reversed order rather than in the _station_combinations_. It is not the best way but it works.  

`if station_combinations and not any(set(station_comb.split('-')) == (
                {station1.rsplit('.', 2)[0], station2.rsplit('.', 2)[0]}
                if '.' in (station_comb) else
                {station1.split('.')[1], station2.split('.')[1]})
                for station_comb in station_combinations):
            continue
        station1_id = '.'.join([station1.split('.')[0], station1.split('.')[1]])
        station2_id = '.'.join([station2.split('.')[0], station2.split('.')[1]])
        which_combination = [
            comb for comb in station_combinations
            if {station1_id, station2_id} == set(comb.split('-'))
        ][0]
        if station1_id == which_combination.split('-')[1]:
            station1, station2 = station2, station1`
