### ISSUE TITLE
Duplicated traces before preprocess, day files, io/data configuration

### ISSUE THREAD

**Issue by alemkhodadadi** [trichter/yam#19]
at the very end lines of the function _getdata_ at _correlate.py_, there is a part, 
```
t1 = stream[0].stats.starttime
t2 = stream[-1].stats.endtime
if t1 - day < 60:
    fname = data.format(t=day - 1, **smeta)
    try:
        stream += obspy.read(fname, data_format, starttime=day - edge)
    except Exception:
        pass
if next_day - t2 < 60:
    endtime = next_day + overlap + edge
    fname = data.format(t=next_day, **smeta)
    try:
        stream += obspy.read(fname, data_format, endtime=endtime)
    except Exception:
        pass
```
I don't understand what exactly this part does, but it leads to duplicating either the first trace or all the traces in the stream. 
I have 31 days of data, but I realized that this function sometimes delivers 32 or 63 traces in the stream, resulting in longer preprocess times.

**Comment by trichter** [comment]
The `get_data()` function loads and returns data for a single day. The reasoning behind loading also parts of the files from the previous and the next day is the following. I often saw day files not beginning exactly at midnight but rather some seconds later (sometimes even minutes later) due to technical issues with the digitizer or the data transfer protocol or whatever reason. Therefore, by default 60 seconds of the previous day are loaded again. By using the `starttime` parameter in the `read()` function not much more than these 60 seconds (`edge` paramter) should be loaded from the previous days. I often calculated xcorrs for hourly time periods, but with an overlap of 30 minutes (`overlap` parameter). To not miss the correlation over midnight, in this case overlap + edge seconds are loaded from the next day. Again, the `endtime` parameter is used to only load the necessary parts of the file of the next day.

Therefore, as a matter of fact, some parts (~overlap+ege seconds) of the data are loaded twice, but for reasons of code readability I did not change this behavior. I also think it should not affect the performance much. (You could simply test by commenting the code block from your comment.)

(Side note: No data is loaded from the previous/next day if there is a data gap at the beginning/end of the day.)

I think the number of traces before merging is not an indicator of the length of the loaded time period, but rather of the gapiness of the data. Are you sure you see duplication?

**Comment by alemkhodadadi** [comment]
you've mentioned that this function returns data for a single day but it loads the data for all the days in my case. 
In my case, I'm using the following configuration in _conf.json_ ,
```
"TR": {
        "startdate": "2018-05-26",
        "enddate": "2018-06-25",
        "length": 3600,
        "overlap": 0,
        "discard": null,
        "filter": [0.5, 10],
        "max_lag": 5,
        "normalization": ["1bit", "spectral_whitening"],
        "taper_after_norm": true,
        "spectral_whitening_options": {"filter": [0.5, 10]},
        "station_combinations": ["OT.PKV-OT.EVV", "OT.TLV-OT.PKV", "OT.PKV-OT.SSV", "OT.PKV-OT.PMV",  "OT.EVV-OT.TLV", "OT.EVV-OT.SSV", "OT.EVV-OT.PMV",  "OT.TLV-OT.SSV", "OT.PMV-OT.TLV", "OT.PMV-OT.SSV", "OT.RSV-OT.SSV", "OT.RSV-OT.TLV", "OT.RSV-OT.EVV", "OT.RSV-OT.PKV", "OT.RSV-OT.PMV"],
        "component_combinations": ["TR"],
        "keep_correlations": false,
        "stack": "1d"
}

```
as I understand the code is supposed to do the cross-correlations day by day and for each day it should take the data for only that specific day. 
Now for 6 stations and 2 components (E, N), the code calls the function `get_data()` 12 times for each day. 
I'm printing some parameters in this function.
1-the input arguments, 
2-`fname` parameter which is generated within the function 
`fname = data.format(t=day, **smeta)`
3-returned stream 

```
smeta : {'network': 'OT', 'station': 'EVV', 'location': '', 'channel': 'DPN'}
data : ../../day_files/{network}.{station}.{location}.{channel}*
day : 2018-05-26T00:00:00.000000Z
fname : ../../day_files/OT.EVV..DPN*
return stream: 32 Trace(s) in Stream:
OT.EVV..DPN | 2018-05-26T00:46:16.987500Z - 2018-05-26T23:13:48.847500Z | 50.0 Hz, 4042594 samples
OT.EVV..DPN | 2018-05-27T00:51:14.987500Z - 2018-05-27T23:10:45.847500Z | 50.0 Hz, 4018544 samples
OT.EVV..DPN | 2018-05-28T00:49:53.987500Z - 2018-05-28T23:09:50.847500Z | 50.0 Hz, 4019844 samples
OT.EVV..DPN | 2018-05-29T00:49:33.987500Z - 2018-05-29T23:10:22.847500Z | 50.0 Hz, 4022444 samples
OT.EVV..DPN | 2018-05-30T00:49:33.987500Z - 2018-05-30T23:11:55.847500Z | 50.0 Hz, 4027094 samples
OT.EVV..DPN | 2018-05-31T00:45:21.987500Z - 2018-05-31T23:13:00.847500Z | 50.0 Hz, 4042944 samples
OT.EVV..DPN | 2018-06-01T00:49:20.987500Z - 2018-06-01T23:11:01.847500Z | 50.0 Hz, 4025044 samples
OT.EVV..DPN | 2018-06-02T01:57:27.987500Z - 2018-06-02T23:10:58.847500Z | 50.0 Hz, 3820544 samples
OT.EVV..DPN | 2018-06-03T00:50:45.987500Z - 2018-06-03T23:12:59.847500Z | 50.0 Hz, 4026694 samples
OT.EVV..DPN | 2018-06-04T00:49:10.987500Z - 2018-06-04T22:18:02.847500Z | 50.0 Hz, 3866594 samples
OT.EVV..DPN | 2018-06-05T00:51:39.987500Z - 2018-06-05T23:10:55.847500Z | 50.0 Hz, 4017794 samples
OT.EVV..DPN | 2018-06-06T00:50:05.987500Z - 2018-06-06T20:08:03.847500Z | 50.0 Hz, 3473894 samples
OT.EVV..DPN | 2018-06-07T00:58:27.987500Z - 2018-06-07T22:59:14.847500Z | 50.0 Hz, 3962344 samples
OT.EVV..DPN | 2018-06-08T00:50:14.987500Z - 2018-06-08T22:28:07.847500Z | 50.0 Hz, 3893644 samples
OT.EVV..DPN | 2018-06-09T00:49:59.987500Z - 2018-06-09T20:08:09.847500Z | 50.0 Hz, 3474494 samples
OT.EVV..DPN | 2018-06-10T00:49:51.987500Z - 2018-06-10T20:48:13.847500Z | 50.0 Hz, 3595094 samples
OT.EVV..DPN | 2018-06-11T00:50:32.987500Z - 2018-06-11T23:09:18.847500Z | 50.0 Hz, 4016294 samples
OT.EVV..DPN | 2018-06-12T00:50:32.987500Z - 2018-06-12T20:30:58.847500Z | 50.0 Hz, 3541294 samples
OT.EVV..DPN | 2018-06-13T00:48:03.987500Z - 2018-06-13T22:55:58.847500Z | 50.0 Hz, 3983744 samples
OT.EVV..DPN | 2018-06-14T00:50:40.987500Z - 2018-06-14T23:12:59.847500Z | 50.0 Hz, 4026944 samples
OT.EVV..DPN | 2018-06-15T00:50:27.987500Z - 2018-06-15T23:16:01.847500Z | 50.0 Hz, 4036694 samples
OT.EVV..DPN | 2018-06-16T00:48:20.987500Z - 2018-06-16T23:10:07.847500Z | 50.0 Hz, 4025344 samples
OT.EVV..DPN | 2018-06-17T00:38:20.987500Z - 2018-06-17T22:16:59.847500Z | 50.0 Hz, 3895944 samples
OT.EVV..DPN | 2018-06-18T00:51:38.987500Z - 2018-06-18T20:31:05.847500Z | 50.0 Hz, 3538344 samples
OT.EVV..DPN | 2018-06-19T00:48:26.987500Z - 2018-06-19T21:01:59.847500Z | 50.0 Hz, 3640644 samples
OT.EVV..DPN | 2018-06-20T00:52:03.987500Z - 2018-06-20T22:26:08.847500Z | 50.0 Hz, 3882244 samples
OT.EVV..DPN | 2018-06-21T00:47:22.987500Z - 2018-06-21T22:45:17.847500Z | 50.0 Hz, 3953744 samples
OT.EVV..DPN | 2018-06-22T00:49:13.987500Z - 2018-06-22T23:16:06.847500Z | 50.0 Hz, 4040644 samples
OT.EVV..DPN | 2018-06-23T00:48:29.987500Z - 2018-06-23T23:10:21.847500Z | 50.0 Hz, 4025594 samples
OT.EVV..DPN | 2018-06-24T00:38:26.987500Z - 2018-06-24T23:10:55.847500Z | 50.0 Hz, 4057444 samples
OT.EVV..DPN | 2018-06-25T00:49:26.987500Z - 2018-06-25T23:09:54.847500Z | 50.0 Hz, 4021394 samples
OT.EVV..DPN | 2018-05-26T00:46:16.987500Z - 2018-05-26T23:13:48.847500Z | 50.0 Hz, 4042594 samples

```
apparently, the parameter _day_ doesn't have any usage to get the data.

**Comment by trichter** [comment]
Please check your configuration for io/data, it should contain one or more `{t}` fields, see e.g.
https://yam.readthedocs.io/en/latest/#example-configuration-file.
The expected behavior using your data string is indeed to load all data for each day.

**Comment by alemkhodadadi** [comment]
You are absolutely right. I didn't pay attention to that. 
Thank you! It works like a charm now! 
I close this issue then.

**Comment by trichter** [comment]
Glad it works for you now!
