### ISSUE TITLE
h5py tables not saved

### ISSUE THREAD

**Issue by bvicic** [trichter/yam#3]
Hi.
I am trying to use yam with some data that I have. When I run the yam --tutorial everything seems to be working OK.

I changed the config file to work on my data and run it with:
yam correlate -vvv 1

everything is finished without errors, the only problem is, that the h5py files are not written to the disc.

I have flagged the config lines like that:

>         # Filenames for results (can also be the same file for all results) and path for plots
>         "corr": "/Volumes/Data/yam/proc/corr.h5",
>         "stack": "/Volumes/Data/yam/proc/stack.h5",
>         "stretch": "/Volumes/Data/yam/proc/stretch.h5",
>         "plot": "/Volumes/Data/yam/proc/plots"
>         },

and 

>                 # weather to save the correlations (here the 1h-correlations)
>                 "keep_correlations": true,
>                 # Stack the correlations (null or "1d" or "xxxh").
>                 # Note, that "keep_correlations": false togehter with "stack": null does not make sense,
>                 # because correlations would not be written to disk and lost.
>                 # Stack can not be larger than "1d" here, because processing is performed on daily data files.
>                 # If you want to stack over a longer time, use the separate stack command.
>                 "stack": "1d"

any idea? 

thanks!
blaz

**Comment by trichter** [comment]
Hi blaz,

some common sources of error are:
* Are `startdate` and `enddate` parameters correct?
* Do you have an inventory including channel information? (It is used to iterate over.)
* Do you have the correct `component_combination` setting? (Setting is not optional.)

I don't now if that matters:
* Does proc directory exist?
* Are you on windows? Try to use windows path separator `\\`.

Does this work:
* `yam info` should show information about station metadata and data files
* `yam print|plot data seedid year-month-day` should print or plot a day of data

**Comment by bvicic** [comment]
Hi, thanks, but I dont see any problems...
- `start` and `enddates` are set correctly.
- inventory is here (`component_coombination=["HHE"]`):

>(obspy) pb-vicic:proc bvicic$ yam info stations 

> Inventory created at 2018-06-04T11:46:05.692020Z
> 	Created by: ObsPy 1.1.0
> 		    https://www.obspy.org
> 	Sending institution: rf (DMG)
> 	Contains:
> 		Networks (2):
> 			SL (2x)
> 		Stations (2):
> 			SL.CRNS (Crni vrh, SL)
> 			SL.JAVS (Javornik, SL)
> 		Channels (27):
> 			SL.CRNS..HHZ (4x), SL.CRNS..HHN (4x), SL.CRNS..HHE (4x), 
> 			SL.JAVS..HHZ (5x), SL.JAVS..HHN (5x), SL.JAVS..HHE (5x)

Yes, proc dir exists, its the work dir where I run the scripts from.
No, I run this on MacOS

`yam info`  gives this:

> (obspy) pb-vicic:proc bvicic$ yam info stations 
> Inventory created at 2018-06-04T11:46:05.692020Z
> 	Created by: ObsPy 1.1.0
> 		    https://www.obspy.org
> 	Sending institution: rf (DMG)
> 	Contains:
> 		Networks (2):
> 			SL (2x)
> 		Stations (2):
> 			SL.CRNS (Crni vrh, SL)
> 			SL.JAVS (Javornik, SL)
> 		Channels (27):
> 			SL.CRNS..HHZ (4x), SL.CRNS..HHN (4x), SL.CRNS..HHE (4x), 
> 			SL.JAVS..HHZ (5x), SL.JAVS..HHN (5x), SL.JAVS..HHE (5x)
> (obspy) pb-vicic:proc bvicic$ yam info
> Stations:
>     SL.CRNS SL.JAVS
>     2 stations, 27 channels
> Raw data (expression for day files):
>     /Volumes/Data/Postojna_yam/data/2009removed_rsp_e/{network}.{station}.{location}.{channel}__{t.year}{t.month:02d}{t.day:02d}.mseed
>     10 files found
> Config ids:
>     c Corr: 1, 1a, auto
>     s Stack: 1, 2
>     t Stretch: 1, 2
> Correlations (channel combinations, correlations calculated):
>     None
> Stacks:
>     None
> Stretching matrices:
>     None

yam print and plot works. 

Thanks for your help! I can also upload the example data.

**Comment by trichter** [comment]
> inventory is here (component_combination=["HHE"])

Wait a moment. It's component combinations not channel combinations. And I was also wrong, its not mandatory. So, try something like `["EE", "EZ", "ZZ"]` or leave it away for all possible combinations.

**Comment by bvicic** [comment]
Oooh! This solved the problem, thank you very much!

**Comment by trichter** [comment]
You are welcome! I am glad to help.
