### ISSUE TITLE
default "float" dtype in stack.py

### ISSUE THREAD

**Issue by filefolder** [trichter/yam#6]
Hi-- was trying to get to the bottom of some memory issues and noticed that numpy now defaults to a dtype of float64 unless specified. In most of the code here this is indeed explicitly set to a sane and reasonable float16 except in stack.py (and also sometimes in commands.py) where it is just "float".

Changing these float instances to a string of 'float16' seems to restore the expected behaviour (of not costing me 3x the ram) unless the issue is something weirder on my end. 

May also be helpful to add an option to set dtype as a kwarg in future releases though I personally don't see a pressing need for this.

**Comment by trichter** [comment]
Thanks for raising this! I will set the default to float16 for future releases.

**Comment by trichter** [comment]
I already updated the master branch by simply replacing all occurrences of `float` with `'float16'`.

**Comment by trichter** [comment]
I think this issue can be closed....
