### ISSUE TITLE
ZR/ZT correlations fail if even ONE station combination has unequal timespan

### ISSUE THREAD

**Issue by filefolder** [trichter/yam#7]
Hi,

I'm noticing that if you send a huge group of station_combinations to correlate.correlate for a certain day, if even one of them causes a problem (typically during the stream.rotate(NE-RT) part) then the whole analysis for that day is tossed out.

What I've done to circumvent this is just add a try: except: pass from line ~661 in correlate.py up until the "#start correlation" comment. This should just skip the individual bad station combination from being added to the tasks and let the rest continue as normal. Haven't tested very thoroughly but seems to be working as expected now.

**Comment by trichter** [comment]
Thanks for letting me know. I will have alook. Can you also post a traceback of the error? Maybe something can be done with the rotate function to make it more flexible.

**Comment by filefolder** [comment]
It's just the standard error in obspy's rotate, "All components need to have the same time span." in https://docs.obspy.org/_modules/obspy/core/stream.html#Stream.rotate

In individual obspy-only instances I would probably leave it to the user to trim as needed, but in this case it becomes tricky when you're throwing thousands of combinations at once. 

I *think* my suggestion is a simple fix, so far so good for me, but there may be some 2nd order effects in other parts of the code I'm not aware of.

**Comment by trichter** [comment]
> typically during the stream.rotate(NE-RT) part

Did you encounter other errors, too? Because I think I do not want to add a general try except clause, because it could hide other more fundamental problems, but a try except catching only this specific error is probably the way how I would implement it.

> something can be done with the rotate function to make it more flexible.

I had something in mind: obspy/obspy#1918

**Comment by filefolder** [comment]
sorry I should have said "exclusively", I only have errors associated with either the N or E channel being a slightly different length. 

That obspy trim common feature would be very handy but may complicate things if one day's xcorr length is randomly shorter than the rest, depending. Perhaps an option to shorten OR toss inconsistent lengths?

**Comment by trichter** [comment]
I am closing this one for now.
