### ISSUE TITLE
suggestion: do not automatically calculate both sides of each component_combination

### ISSUE THREAD

**Issue by filefolder** [trichter/yam#8]
Hi again, 

Wondering if it makes sense to change the code so that a requested component combination (e.g. 'RZ') produces ONLY _sta1_R-sta2_Z_ data instead of BOTH _sta1_R-sta2_Z_ and the mirrored _sta1_Z-sta2_R_ data. It'd still be easy to get both by just requesting both in the component_combinations (e.g. 'RZ', 'ZR') array but sometimes you only need the one pair in half the time.

I tend to use the code's functions individually as parts of other code rather than in aggregate or via the tutorials so maybe in that sense the suggestion isn't appropriate, but fwiw. In any event if anyone else is running into this, this is easily hacked by removing the `and comps[::-1] not in component_combinations` part of the IF statement ~line 675 in correlate.py

**Comment by trichter** [comment]
Hi again,

I am happy for every feedback.

I don't know if it makes sense. Probably most often you want everything that you can get? In this case RZ and ZR. Therefore I tend to leave it as it is now. In case of doubt, I also think it is better to calculate more combinations than less.

:+1: for sharing your work-around.

**Comment by filefolder** [comment]
Yep can't disagree for the mostpart. In my case (correcting sensor alignment via ASN) it can be a nice shortcut. I'll just close and if it helps anyone, great. 

Perhaps one day if you're looking for extra work you could allow a user to set the combo `_ZR_` or something to explicitly request that set only. e.g.

~606 correlate.py
```
do_oneway=False
if '_' in components: do_oneway=True; components.remove('_')
```

~674
...`and (comps[::-1] not in component combinations AND not do_oneway)`
