### ISSUE TITLE
account for rotated sensors in inventory in baz/azi calculation

### ISSUE THREAD

**Issue by filefolder** [trichter/yam#9]
Getting a bit hyper-specialised now but I find that I have to deal with sites that are significantly out of north alignment somewhat regularly, dealt with by manually changing the sensor channel azimuths in the inventory metadata. However in re-deriving xcorrs I notice that the azi/baz are still just calculated via station lat/lon position alone so the misalignment problems persist.

A fix seems painless enough but I'm struggling with the trig a bit honestly. Which is to say I have not tested it (yet)
 
~line 660 correlate.py
```
dist,azi,baz = gps2dist_azimuth(*args)
dtheta = (inventory.get_orientation(stream1[0].id,datetime=datetime1)['azimuth'] \
       - inventory.get_orientation(stream2[0].id,datetime=datetime2)['azimuth']) %360
if dtheta > 180: dtheta-=360
azi = (azi - dtheta)%360
baz = (azi+180)%360
```

**Comment by trichter** [comment]
That would be a nice addition. To be honest, I myself never actually used the rotation features. Terefore it's nice, that you do.

Misaligned sensors would also affect ZNE correlations and could be handled with a new option `correct_sensor_rotation=False/True` or similar. What about the vertical misalignment? All of this could be easily handled with `Stream.rotate('->ZNE', inventory=inventory)`.

**Comment by filefolder** [comment]
Ahh yes I forgot about that particular self-rotate function, seems perfect for this. Where would it go?

Only concern maybe is the extra CPU needed required to rotate the streams. My understanding is that simply fixing the azi variable has the same net effect but only costs a few math problems (if I can ever figure them out.. edited my post above with my 2nd attempt).

**Comment by trichter** [comment]
Probably in `preprocess`, before the normalization? This means between the calls to _prep1 and _prep2.

> Only concern maybe is the extra CPU needed to rotate the streams. My understanding is that simply fixing the azi variable has the same net effect but only costs a few math problems (if I can ever figure them out.. edited my post above with my 2nd attempt).

Yes, right, but better slow than wrong ;). Also this needs to be done only once per station, not for each station combination. Best solution would be adding `'->ZRT'` case to obspy.

**Comment by filefolder** [comment]
FWIW I couldn't get the rotation to stick all the way through if I put it either before preprocess or between the prep1 & prep2 calls... couldn't figure out where or how it was getting lost though. 

however putting the below following the stream1 and stream2 definitions ~line 650, works as expected.

thanks for the help!

```
if inventory.get_orientation(stream1[0].id,datetime=datetime1)['azimuth'] != 0: stream1.rotate('->ZNE',inventory=inventory)
if inventory.get_orientation(stream2[0].id,datetime=datetime2)['azimuth'] != 0: stream2.rotate('->ZNE',inventory=inventory)
```

**Comment by trichter** [comment]
Please reopen if needed.
